apiVersion: v1
kind: Service

metadata:
  name: fraud-service

spec:
  selector:
    app: fraud-service

  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}

  type: {{ .Values.service.type }}